// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexShift.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexShift.Infrastructure.Migrations
{
    [DbContext(typeof(NexShiftDbContext))]
    [Migration("20260307032138_AddBacklogRulesWithSeed")]
    partial class AddBacklogRulesWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexShift.Core.Entities.BacklogRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Pattern");

                    b.ToTable("BacklogRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Este archivo usa WCF que no existe en .NET moderno.",
                            IsActive = true,
                            Pattern = "ServiceContract",
                            Reason = "Migrar manualmente a gRPC (recomendado) o REST. Ver: aka.ms/wcf-migration",
                            Title = "WCF Service detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Este archivo usa WCF que no existe en .NET moderno.",
                            IsActive = true,
                            Pattern = "OperationContract",
                            Reason = "Migrar manualmente a gRPC (recomendado) o REST. Ver: aka.ms/wcf-migration",
                            Title = "WCF Service detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Este archivo usa WCF que no existe en .NET moderno.",
                            IsActive = true,
                            Pattern = "System.ServiceModel",
                            Reason = "Migrar manualmente a gRPC (recomendado) o REST. Ver: aka.ms/wcf-migration",
                            Title = "WCF Service detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Los controles Web Forms no tienen equivalente en .NET moderno.",
                            IsActive = true,
                            Pattern = "System.Web.UI",
                            Reason = "La lógica del Code Behind puede rescatarse. La UI debe reescribirse en Razor Pages o Blazor.",
                            Title = "ASP.NET Web Forms detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Los controles Web Forms no tienen equivalente en .NET moderno.",
                            IsActive = true,
                            Pattern = "Page_Load",
                            Reason = "La lógica del Code Behind puede rescatarse. La UI debe reescribirse en Razor Pages o Blazor.",
                            Title = "ASP.NET Web Forms detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Los controles Web Forms no tienen equivalente en .NET moderno.",
                            IsActive = true,
                            Pattern = "ViewState",
                            Reason = "La lógica del Code Behind puede rescatarse. La UI debe reescribirse en Razor Pages o Blazor.",
                            Title = "ASP.NET Web Forms detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FormsAuthentication no existe en .NET moderno.",
                            IsActive = true,
                            Pattern = "FormsAuthentication",
                            Reason = "Decisión requerida: ¿JWT + Identity, Azure AD, Auth0? El motor no puede elegir por vos.",
                            Title = "Autenticación legacy detectada",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "WindowsIdentity requiere decisión arquitectural.",
                            IsActive = true,
                            Pattern = "WindowsIdentity",
                            Reason = "Decisión requerida: ¿JWT + Identity, Azure AD, Auth0? El motor no puede elegir por vos.",
                            Title = "Autenticación legacy detectada",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Este código lee/escribe el Registry de Windows.",
                            IsActive = true,
                            Pattern = "Microsoft.Win32.Registry",
                            Reason = ".NET moderno es multiplataforma. Migrar a appsettings.json, Azure Key Vault o variables de entorno.",
                            Title = "Windows Registry detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Este código lee/escribe el Registry de Windows.",
                            IsActive = true,
                            Pattern = "RegistryKey",
                            Reason = ".NET moderno es multiplataforma. Migrar a appsettings.json, Azure Key Vault o variables de entorno.",
                            Title = "Windows Registry detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dependencia de DLL nativa de Windows.",
                            IsActive = true,
                            Pattern = "DllImport",
                            Reason = "Evaluar si existe alternativa cross-platform. Si no, la app debe correr en Windows.",
                            Title = "COM Interop / P/Invoke detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dependencia de DLL nativa de Windows.",
                            IsActive = true,
                            Pattern = "ComVisible",
                            Reason = "Evaluar si existe alternativa cross-platform. Si no, la app debe correr en Windows.",
                            Title = "COM Interop / P/Invoke detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patrones de EF6 que no existen en EF Core.",
                            IsActive = true,
                            Pattern = "Database.SetInitializer",
                            Reason = "Database.SetInitializer → EF Core Migrations. Revisar lazy loading y transacciones.",
                            Title = "Entity Framework 6 incompatible con EF Core",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "ManualRequired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Namespace de EF6 detectado.",
                            IsActive = true,
                            Pattern = "System.Data.Entity",
                            Reason = "Reemplazar por Microsoft.EntityFrameworkCore. Revisar breaking changes en lazy loading.",
                            Title = "Entity Framework 6 incompatible con EF Core",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clase estática detectada.",
                            IsActive = true,
                            Pattern = "static class",
                            Reason = "Evaluar si debe ser Scoped, Singleton o Transient en el contenedor de DI de .NET.",
                            Title = "Clase estática — candidata a DI",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GDI+ depende de librerías nativas de Windows.",
                            IsActive = true,
                            Pattern = "System.Drawing",
                            Reason = "En Linux/Azure va a fallar. Migrar a SkiaSharp o ImageSharp.",
                            Title = "System.Drawing / GDI+ detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = ".Result detectado sin async/await.",
                            IsActive = true,
                            Pattern = ".Result",
                            Reason = "Causa deadlocks en ASP.NET Core. Convertir a async/await con cuidado.",
                            Title = "Código sincrónico bloqueante",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bloquea el thread en lugar de usar async.",
                            IsActive = true,
                            Pattern = "Thread.Sleep",
                            Reason = "Reemplazar por await Task.Delay() en contexto async.",
                            Title = "Thread.Sleep detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso estático a HttpContext.",
                            IsActive = true,
                            Pattern = "HttpContext.Current",
                            Reason = "Inyectar IHttpContextAccessor en lugar del static. Puede causar NullReference en .NET moderno.",
                            Title = "HttpContext.Current detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lectura de configuración vía App.config.",
                            IsActive = true,
                            Pattern = "ConfigurationManager.AppSettings",
                            Reason = "Reemplazar por IConfiguration inyectado. Web.config fue migrado a appsettings.json automáticamente.",
                            Title = "ConfigurationManager detectado",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline OWIN detectado.",
                            IsActive = true,
                            Pattern = "Microsoft.Owin",
                            Reason = "Migrar a middleware nativo de ASP.NET Core. Program.cs fue generado como punto de partida.",
                            Title = "OWIN / Katana middleware",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Category = "NeedsReview",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipeline OWIN detectado.",
                            IsActive = true,
                            Pattern = "IAppBuilder",
                            Reason = "Migrar a middleware nativo de ASP.NET Core. Program.cs fue generado como punto de partida.",
                            Title = "OWIN / Katana middleware",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NexShift.Core.Entities.MigrationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MigrationJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("MigrationIssues");
                });

            modelBuilder.Entity("NexShift.Core.Entities.MigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("OutputZipPath")
                        .HasColumnType("text");

                    b.Property<string>("ReportMarkdown")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("NexShift.Core.Entities.NugetPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyAdded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SuggestedReplacement")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NugetPackages");
                });

            modelBuilder.Entity("NexShift.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeprecatedPackages")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedFramework")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean");

                    b.Property<int>("MigrationScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCsFiles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPackages")
                        .HasColumnType("integer");

                    b.Property<int>("TotalProjects")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("NexShift.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GitHubAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("ReposUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NexShift.Core.Entities.MigrationIssue", b =>
                {
                    b.HasOne("NexShift.Core.Entities.MigrationJob", "MigrationJob")
                        .WithMany("Issues")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("NexShift.Core.Entities.MigrationJob", b =>
                {
                    b.HasOne("NexShift.Core.Entities.Repository", "Repository")
                        .WithMany("MigrationJobs")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("NexShift.Core.Entities.Repository", b =>
                {
                    b.HasOne("NexShift.Core.Entities.User", "User")
                        .WithMany("Repositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexShift.Core.Entities.MigrationJob", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("NexShift.Core.Entities.Repository", b =>
                {
                    b.Navigation("MigrationJobs");
                });

            modelBuilder.Entity("NexShift.Core.Entities.User", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
